site_name: Dance Docs
site_url: https://jakegatsby.github.io/dance/
docs_dir: src
theme:
  name: material
  palette:
  - scheme: slate
extra_css:
- stylesheets/custom.css
nav:
- Home: index.md
- Syllabi:
  - "East Coast Swing": syllabi/east-coast-swing.md
  - Foxtrot: syllabi/foxtrot.md
  - Hustle: syllabi/hustle.md

