site_name: Dance Docs
site_url: https://jakegatsby.github.io/dance/
docs_dir: src
theme:
  name: material
  palette:
  - scheme: slate
nav:
- Home: index.md
- Syllabi:
  - Hustle: syllabi/hustle.md
  - "East Coast Swing": syllabi/east-coast-swing.md
